/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/credentials` | `/signup/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/seed-phrase` | `/signup/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/modals/credentials` | `/signup/modals/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/modals/seed-phrase` | `/signup/modals/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/credentials` | `/signup/credentials`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/seed-phrase` | `/signup/seed-phrase`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/modals/credentials` | `/signup/modals/credentials`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/modals/seed-phrase` | `/signup/modals/seed-phrase`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/credentials${`?${string}` | `#${string}` | ''}` | `/signup/credentials${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/seed-phrase${`?${string}` | `#${string}` | ''}` | `/signup/seed-phrase${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/modals/credentials${`?${string}` | `#${string}` | ''}` | `/signup/modals/credentials${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/modals/seed-phrase${`?${string}` | `#${string}` | ''}` | `/signup/modals/seed-phrase${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/credentials` | `/signup/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/seed-phrase` | `/signup/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/modals/credentials` | `/signup/modals/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/modals/seed-phrase` | `/signup/modals/seed-phrase`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
