/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/credentials` | `/create/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/seed-phrase` | `/create/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/modals/credentials` | `/create/modals/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/modals/seed-phrase` | `/create/modals/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/import` | `/import`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create/credentials` | `/create/credentials`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create/seed-phrase` | `/create/seed-phrase`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create/modals/credentials` | `/create/modals/credentials`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/create/modals/seed-phrase` | `/create/modals/seed-phrase`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/import` | `/import`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create/credentials${`?${string}` | `#${string}` | ''}` | `/create/credentials${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create/seed-phrase${`?${string}` | `#${string}` | ''}` | `/create/seed-phrase${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create/modals/credentials${`?${string}` | `#${string}` | ''}` | `/create/modals/credentials${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/create/modals/seed-phrase${`?${string}` | `#${string}` | ''}` | `/create/modals/seed-phrase${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/import${`?${string}` | `#${string}` | ''}` | `/import${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/credentials` | `/create/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/seed-phrase` | `/create/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/modals/credentials` | `/create/modals/credentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/create/modals/seed-phrase` | `/create/modals/seed-phrase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/import` | `/import`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
